### ISSUE TITLE
Different outputs for same sequences?

### ISSUE THREAD

**Issue by Bernadetadad** [BackofenLab/IntaRNA#106] opened 2017-11-20 18:11 UTC
Hi, 
I was wondering what's the reason for different outputs when two equal length RNAs are switched between query and target? 
For example:
 `intarna -q CCCAUCGGAUUCUUCCUUCAGAAUCCGCUCCACUAUCUGCUUUCC  -t ACUUUGCUUUGGUGGAGCGGCUGCAAAGGGAAGAAGUUUUAUUAU --seedBP=4 
`
versus

`intarna -q ACUUUGCUUUGGUGGAGCGGCUGCAAAGGGAAGAAGUUUUAUUAU  -t CCCAUCGGAUUCUUCCUUCAGAAUCCGCUCCACUAUCUGCUUUCC --seedBP=4 
`
gives different results.

**Comment by martin-mann** [comment] 2017-11-20 21:04
Hi @Bernadetadad 

which version of IntaRNA are you using? With the current I get the following:

```[bash]
 --> IntaRNA -q CCCAUCGGAUUCUUCCUUCAGAAUCCGCUCCACUAUCUGCUUUCC  -t ACUUUGCUUUGGUGGAGCGGCUGCAAAGGGAAGAAGUUUUAUUAU --seedBP=4

target
            10       18
             |       |
 5'-ACUUUGCUU         GGCU...UAU-3'
             UGGUGGAGC
             |:|||||||
             AUCACCUCG
3'-CCU...GUCU         CCUA...CCC-5'
             |       |
            35       27
query

interaction energy = -9.58888 kcal/mol


 --> IntaRNA -t CCCAUCGGAUUCUUCCUUCAGAAUCCGCUCCACUAUCUGCUUUCC  -q ACUUUGCUUUGGUGGAGCGGCUGCAAAGGGAAGAAGUUUUAUUAU --seedBP=4

target
            27       35
             |       |
5'-CCC...AUCC         UCUG...UCC-3'
             GCUCCACUA
             |||||||:|
             CGAGGUGGU
3'-UAU...UCGG         UUCGUUUCA-5'
             |       |
            18       10
query

interaction energy = -9.58888 kcal/mol
```

which is absolutely correct since the target is always shown on top. when you swap query and target in the input, the former target sequence is now shown in reverse order on the bottom. the interaction is still the same (former target 10-18, former query 27-35).

therefore the question: was it just an interpretation issue or do you get different results? in the latter case, please report intarna version (and if you compiled from source or installed some package), vienna rna version, and operating system.

Thanks,
Martin

**Comment by Bernadetadad** [comment] 2017-11-20 21:44
Hi, 

Thanks for the response. I use 2.0.4. 

intarna --version
IntaRNA 2.0.4

—> intarna -q CCCAUCGGAUUCUUCCUUCAGAAUCCGCUCCACUAUCUGCUUUCC  -t ACUUUGCUUUGGUGGAGCGGCUGCAAAGGGAAGAAGUUUUAUUAU --seedBP=4

target
            10         20
             |         |
 5'-ACUUUGCUU           CUGC...UAU-3'
             UGGUGGAGCGG
             |:|||||||||
             AUCACCUCGCC
3'-CCU...GUCU           UAAG...CCC-5'
             |         |
            35         25
query

interaction energy = -10.5071 kcal/mol

—>intarna -t CCCAUCGGAUUCUUCCUUCAGAAUCCGCUCCACUAUCUGCUUUCC  -q ACUUUGCUUUGGUGGAGCGGCUGCAAAGGGAAGAAGUUUUAUUAU --seedBP=4

target
            10                        35
             |                        |
 5'-CCCAUCGGA         CA AAU           UCUG...UCC-3'
             UUCUUCCUU  G   CCGCUCCACUA
             |||||||:|  |   |||||||||:|
             AAGAAGGGA  C   GGCGAGGUGGU
3'-UAU...UUUG         AA GUC           UUCGUUUCA-5'
             |                        |
            35                        10
query

interaction energy = -13.1561 kcal/mol


I also get the same in the online version, here are the links to the two different outputs:
http://rna.informatik.uni-freiburg.de:80/RetrieveResults.jsp?jobID=0978801&toolName=IntaRNA <http://rna.informatik.uni-freiburg.de/RetrieveResults.jsp?jobID=0978801&toolName=IntaRNA>

http://rna.informatik.uni-freiburg.de:80/RetrieveResults.jsp?jobID=1541357&toolName=IntaRNA <http://rna.informatik.uni-freiburg.de/RetrieveResults.jsp?jobID=1541357&toolName=IntaRNA>

**Comment by martin-mann** [comment] 2017-11-20 22:05
uaks, I see... I used the development version in which we have unitized the accessibility computations.

In the old releases (originating from v1.*), accessibility penalties were computed for short queries using a different implementation (like RNAup the non-heuristic method) than for the targets. this was changed last weerk in the dev-version, which now applies the same method to all sequences (window-based computation as done by RNAplfold).

Thus, all IntaRNA versions <= 2.1.0 will show slightly different ED penalties when using the same sequence as query or target and one has length < 150nt, which can result in different predictions as you have encountered. 
Even more so since the window-based approach is only reporting values above a certain threshold while the RNAup-like computation results comes without threshold...

This issue will be fixed with the next release (hopefully this or next week), which applies the same method to all sequences independently of length and whether query or target.

Sorry for the mess.. it is so far inherited from the initial IntaRNA version 1 design, which took it from its non-heuristic "predecessor" RNAup, which used this mixed setup since the window-based approach is the only feasible way for typically long target sequences.

**Comment by martin-mann** [comment] 2017-11-23 15:15
@Bernadetadad I thought further about the problem you sketched and eventually found the true reason: the *heuristic* used to predict the interactions! there is neither a bug nor something wrong with IntaRNA. The stuff I mentioned/discussed above does not apply to your short sequences.

Maybe a short idea what is causing the different prediction results: in the heuristic mode, IntaRNA stores for each leftmost intermolecular base pair only the best score of an interaction extending to the right *including* ED penalties! 
When computing this value for some leftmost base pair `(i1,i2)`, IntaRNA evaluates the ED-penalized initialization of an interaction with the single base pair and all possible right-side extensions with base pair stackings or interior loops, where I name the stacking/loop-closing base pair `(k1,k2)`. Given these two base pairs, it evaluates the energy of a resulting interaction by 
```
 E(i1,i2,k1,k2) = E_loop(i1,i2,k1,k2) + E(k1,j1,k2,j1) -ED1(k1,j1) -ED2(k2,j2) + ED1(i1,j1) + ED2(i2,j2)
```
where `(j1,j2)` are the right ends of the similarly identified best interaction with leftmost base pair `(k1,k2)`. 

The problem is: the direct application of the ED-penalties can result in a low/bad overall energy of short interactions, which are thus discarded and not considered as right-extension of longer interactions. Thus, the computation order (here right to left, i.e. with decreasing target sequence indices) of interactions with such a heuristic influences the result. When reversing the computation order (what you do by swapping query and target), the result can be different, as you observe.

This is both a qualitative 'weakness' of IntaRNA which on the other hand enables its speed (compared to the exact prediction mode via "--mode=S" see [prediction modes](https://github.com/BackofenLab/IntaRNA#predModes). If you are only dealing with such short sequences and want to be sure you get the globally optimal (mfe) interaction, you might consider to use this prediction mode rather than the default heuristic one, which might show this issue.

Hope this clearifies the issue.

**Closed** 2017-11-23 16:23 UTC
