### ISSUE TITLE
Exception related to pf_scale

### ISSUE THREAD

**Issue by AbeerMM** [BackofenLab/IntaRNA#209] opened 2023-01-29 18:30 UTC
Hi,

I'm running IntaRNA with these settings:
`IntaRNA -v --energyVRNA=/home/ubuntu/ViennaRNA-2.5.1/misc/rna_turner2004.par --threads=8 --model=P --mode=M --outMode=C --noSeed --accW=0 --accL=0 --intLenMax=25 -t <my target> -q <my query>`

My target sequence is very long (> 3000nt). I get multiple warnings then two exceptions:
<img width="976" alt="image" src="https://user-images.githubusercontent.com/17438932/215347961-c0ff6024-f985-4cf4-92ec-30ee999b5b79.png">

Is there a way to increase the pf_scale as suggested?

Thank you

**Comment by martin-raden** [comment] 2023-02-01 17:01
Hi, the problem is not with IntaRNA but withe the ViennaRNA library used to compute the accessibility.

The `pf_scale` parameter is used to keep the extreemly large partition function values (for long RNAs) within managable ranges with some computational tricks. The ViennaRNA developers implemented various things to dynamically adapt the parameter, to keep things working for large RNAs.

It seems, the tricks were not working for your RNA and the error reported stems from within the library.. 

https://github.com/ViennaRNA/ViennaRNA/blob/master/src/ViennaRNA/part_func.c#L400/part_func.c#L400

Unfortunately, there is no parameter in IntaRNA to alter `pf_scale`.

The only workaround would be to

- run RNAplfold manually using similar parameters as when calling IntaRNA as discussed [here](https://github.com/BackofenLab/IntaRNA#readwrite-accessibility-fromto-file-or-stream)
  - it supports the `-S`/`--pfScale` argument to alter the parameter, see [manual](https://www.tbi.univie.ac.at/RNA/RNAplfold.1.html)
  - store the output in a file
  - load accessibilities from this file when calling IntaRNA

Sorry for not having another possibility at hand. Please leave the issue open. Hope to find some time to incorporate a respective option into IntaRNA, but this needs some time that I dont have at the moment.. 😢 

Best,
Martin

**Comment by martin-raden** [comment] 2023-02-01 17:04
Alternatively (just noticed in your call): reduce "--accW"... should also reduce the problem! (right now you are trying to compute "exact" accessibilities for the WHOLE sequence, which are most likely wrong for such sequences anyway.. that's exactly why windows-based computation was developed: beside reduced runtime it focusses on local structure rather than extreeemly long base pairs (that are unlikely for many types of RNA)..

**Comment by martin-raden** [comment] 2023-02-02 16:01
Hi @AbeerMM 
fortunately, I found unexpectedly some time to look into the issue and a solution how to integrate the partition function scaling into the IntaRNA interface. This will be part of the upcoming version of IntaRNA.

You can use the feature already by downloading the [3.4.beta version](http://www.bioinf.uni-freiburg.de/~mmann/Downloads/intaRNA-3.4.0.beta.tar.gz) from my space OR by cloning the recent version from GitHub.

You find respective [pfScale documentation already on GitHub](https://github.com/BackofenLab/IntaRNA#accPfScale) (thanks for the error image!)

Hope that helps.
Best,
Martin

**Closed** 2023-02-02 16:01 UTC

**Comment by AbeerMM** [comment] 2023-02-08 22:50
> Alternatively (just noticed in your call): reduce "--accW"... should also reduce the problem! (right now you are trying to compute "exact" accessibilities for the WHOLE sequence, which are most likely wrong for such sequences anyway.. that's exactly why windows-based computation was developed: beside reduced runtime it focusses on local structure rather than extreeemly long base pairs (that are unlikely for many types of RNA)..

@martin-raden Thank you so much for taking the time to resolve the issue and answer my question.
About --accW=0, the reason why I used this value was based on the documentation of IntaRNA. I was trying to reproduce similar results to RNAup calculation. 

I'm working with novel lncRNAs that have length range between couple hundreds to couple thousands. if you could recommend some options that give me the most reliable results, I'd appreciate it. 

Thank you

**Comment by martin-raden** [comment] 2023-02-09 08:27
Hi @AbeerMM ,
you are welcome. 

Concerning your question what accessibility contraints to use for lncRNA.. mhh.. hard to say and I havent worked with them so far. 

It boils down to the question: what is the maximal distance between base pair partners you want to consider/allow? For mRNAs, most people restrict that a lot with the assumption that "full structure formation", i.e. between any segments of the mRNA, is hindered by the continuous translation process and the involved molecules. Thus, a "local folding" using a window-based approach is reasonable and (beside runtime reduction) might exclude artificially long base pairing (eg of sequence ends etc.).

For lncRNA, there is (as far as I know) often no such continous processing and the RNAs can form whatever structure they want.. Thus, local folding will not show you the full (accessibility) figure of your RNA and might even consider regions accessible that are occupied by long range interactions. Thus, your selection of an RNAup-like full-range accessibility computation (accw=0) without bp-span constraint (accL=0) is a reasonable choice, but computationally demanding.

This is one of the reasons, why in [mechRNA](https://academic.oup.com/bioinformatics/article/34/18/3101/4959546?login=false) still local folding (accW=200 accL=150) is applied for both lncRNAs and the target genomes, even with the knowledge that this is only an estimate.

Does this help? :)

Best,
Martin
